### ISSUE TITLE
can we create tags and run with this framework

### ISSUE THREAD

**Issue by bharatk89** [browserstack/junit-browserstack#17]
Hi Team,

Recently I am facing an issue where I am supposed to run smoke testing which is the subset of the test scripts. Is it possible if we can do with this framework and if so how that can be done ?

Can we add tags like @smoke or @regression so we can categorize the test scripts?

**Comment by agarwalswapnil** [comment]
Hi @bharatk89 ,
This repository is an example of how to run tests on BrowserStack.

You can definitely execute only selected tests. 
Try using [Surefire plugin](https://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html) or Google for more options.
