### ISSUE TITLE
Inconsistent env variable to BStack Documentation

### ISSUE THREAD

**Issue by sid-patki-bstack** [browserstack/junit-browserstack#24]
The access key variable name in the BrowserStackJUnitTest.java & conf.json files is inconsistent with the documentation & needs to be updated as it throws an Invalid username or password error if we [set environment variables](https://automate.browserstack.com/dashboard/v2/quick-start/integrate-test-suite-step#setup-authentication) for BrowserStack credentials as per the documentation.
<img width="581" alt="Screenshot 2021-03-20 at 12 23 45 AM" src="https://user-images.githubusercontent.com/80692638/111829649-f6534100-8912-11eb-9cf1-17d81392aeca.png">

<img width="1143" alt="Screenshot 2021-03-20 at 12 28 05 AM" src="https://user-images.githubusercontent.com/80692638/111829835-387c8280-8913-11eb-995b-e4ea936b2270.png">

**Comment by dharmendrajha** [comment]
Hey @sid-patki-bstack, the correct environment variable name is BROWSERSTACK_ACCESS_KEY and the same has been corrected in the Quick Integration Guide.
